# Generated by Django 4.1.2 on 2023-01-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='nacionaldiad',
        ),
        migrations.AddField(
            model_name='autor',
            name='muerte',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='nacimiento',
            field=models.DateField(null=True),
        ),
    ]
