# Generated by Django 4.1.2 on 2023-01-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_remove_autor_edad_remove_autor_nacionaldiad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='muerte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
