# Generated by Django 4.1.2 on 2023-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0003_alter_autor_muerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
