# Generated by Django 4.1.2 on 2023-01-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0004_autor_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='edad',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
