# Generated by Django 4.1.2 on 2023-01-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_remove_lector_edad_remove_lector_nacionaldiad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='muerte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
