# Generated by Django 4.1.2 on 2023-01-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_lector_muerte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='muerte',
        ),
    ]
