# Generated by Django 4.1.2 on 2023-01-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0004_remove_lector_muerte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lector', 'verbose_name_plural': 'Autores'},
        ),
    ]
